---
- name: apt-get update
  raw: "apt-get -y update -qq"
- name: install python
  raw: "apt-get -y install python2.7 python-pip"
- action: setup
- name: install flask
  pip:
    name: flask
- name: copy flask app file
  copy:
    src: spark-ro.py
    dest: /home/ubuntu/spark-ro.py
    owner: ubuntu
    group: ubuntu
    mode: 0755
- name: copy flask systemd file
  copy:
    src: flask.service
    dest: /etc/systemd/system/flask.service
    owner: root
    group: root
    mode: 0755
- name: enable flask service
  systemd:
    state: restarted
    enabled: yes
    daemon_reload: yes
    name: flask.service
